version: "3"
services:
  ui:
    build: ./src/ui
    volumes:
      - ./src/ui:/ui
      - /ui/node_modules
    ports:
      - 3000:3000
    container_name: mvw_ui
    depends_on:
      - api
  api:
    build: ./src/api
    environment:
      - TOKEN_SECRET=${TOKEN_SECRET}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./src/api:/api
      - /api/node_modules
    ports:
      - 8000:8000
    container_name: mvw_api
    depends_on:
      - flyway
  flyway:
    image: boxfuse/flyway:5.2.1
    command: -url=jdbc:postgresql://db:5432/mvw -user=postgres -password=${POSTGRES_PASSWORD} -connectRetries=60 migrate
    volumes:
      - ./sql:/flyway/sql
    container_name: mvw_flyway
    depends_on:
      - db
  db:
    image: postgres:11.7
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=mvw
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    container_name: mvw_db

volumes:
  db-data:
